

// DEBUG
//
#define SERIAL_DEBUG_ON 1
#define SERIAL_DEBUG_ALARMS 1
#define SERIAL_DEBUG_BUTTONS 1
#define SERIAL_DEBUG_CALIBRATION 1
#define SERIAL_DEBUG_DISPLAY 1
#define SERIAL_DEBUG_EEPROM 1
#define SERIAL_DEBUG_EVENTS 1
#define SERIAL_DEBUG_MACHINE 1
#define SERIAL_DEBUG_MAIN_LOOP_TIME 1
#define SERIAL_DEBUG_MENU 1
#define SERIAL_DEBUG_PARAMETERS 1
#define SERIAL_DEBUG_SCHEDULER 1
#define SERIAL_DEBUG_SENSORS 1

// STALE STERUJACE
//
#define EVENTS_QUEUE_SIZE 10

// ALARMY
//
#define MUTE_ALARMS 1   // obsluga zrealizowana w events.h w PushEvent()

//  START PRZYCISKIEM
//
#define BEGIN_WITH_SPECIFIC_ACTION 0
#define USE_SPECIFIC_ACTION 1