enum ErrorEnum
{
	OK =0,
	COMPONENT_IS_ALREADY_BUSY,
	REFERENCE_NOT_SET,
	SENSOR_IO_POINTER_MISSING,
	SENSOR_REFERENCE_MISSING,
	SENSOR_POINTER_MISSING,
	BASIC_SENSOR_WITH_AVERAGING_DIFFERENCE_TO_BIG,
	BASIC_SENSOR_WITH_AVERAGING_VALUE_TOO_LOW,
	BASIC_SENSOR_WITH_AVERAGING_VALUE_TOO_HIGH,
	HEATER_SENSOR_REFERENCE_MISSING,
	HEATER_IO_REFERENCE_MISSING,
	HEATER_TEMPERATURE_TOO_HIGH,
	HEATER_TEMPERATURE_TOO_LOW,
	HEATER_CONTROLLER_INVALID_ZONE_NUMBER,
	HEATER_CONTROLLER_TOO_MANY_HEATERS_TO_ADD,
	HEATER_CURRENT_TO_HIGH,
	UVCROSSLINKING_ALREADY_BUSY,
	UVCROSSLINKING_LESS_THEN_MINIMAL_POWER,
	UVCROSSLINKING_MORE_THEN_MAXIMAL_POWER
};